apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert -f docker-compose-e2e.yaml
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: fabric-kafka2
  name: fabric-kafka2
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fabric-kafka2
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka2.kopernik.ibm.org"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "3"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "103809024"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          value: "2"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "103809024"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper0.kopernik.ibm.org:2181,zookeeper1.kopernik.ibm.org:2181,zookeeper2.kopernik.ibm.org:2181
        image: hyperledger/fabric-kafka
        name: kafka2
        ports:
        - containerPort: 9092
        resources: {}
      dnsConfig:       
        options:       
          - name: ndots
            value: "1" 
status: {}
