apiVersion: v1
kind: Service
metadata:
  name: fabric-ca-org2
  labels:
    app: fabric-ca-org2
spec:
  ports:
  - port: 7054
    targetPort: 7054
  selector:
    app: fabric-ca-org2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fabric-ca-org2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fabric-ca-org2
    spec:
      containers:
      - name: fabric-ca-org2
        image: hyperledger/fabric-ca
        imagePullPolicy: Never
        ports:
        - containerPort: 7054
        command: ["fabric-ca-server", "start", "--ca.certfile", "/etc/hyperledger/fabric-ca-server-config/ca.org2.kopernik.ibm.org-cert.pem", "--ca.keyfile", "/etc/hyperledger/fabric-ca-server-config/f8778592b8210f1e14fba897ef2f7b0cf8346d61bab94368003474d9762d7f22_sk", "-b", "admin:adminpw", "-d"]
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server-config
          name: org2-ca-volume
        env:
        - name: FABRIC_CA_HOME
          value: "/etc/hyperledger/fabric-ca-server"
        - name: FABRIC_CA_SERVER_CA_NAME
          value: "ca-org2"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: "/etc/hyperledger/fabric-ca-server-config/ca.org2.kopernik.ibm.org-cert.pem"
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: "/etc/hyperledger/fabric-ca-server-config/f8778592b8210f1e14fba897ef2f7b0cf8346d61bab94368003474d9762d7f22_sk"
      volumes:
      - name: org2-ca-volume
        hostPath:
          path: /home/hlbcadmin/Downloads/mysolution/fabric-e2e-custom/crypto-config/peerOrganizations/org2.kopernik.ibm.org/ca
